mod bit;
pub mod buf;
pub mod clang;
pub mod generator;
pub mod lexer;
pub mod loc;
pub mod parser;
pub mod tac;
pub mod tac_generator;
pub mod token;
pub use bit::Bit;
mod reg_alloc;
pub use reg_alloc::reg_alloc;
mod static_analysis;
pub use static_analysis::static_analysis;
mod dom;
